Keep logfiles for combined test summaries;  provide more failure and error categories in email message.
Tested on jam, colonelk, amani, pegdub & talwit.

diff --git a/bin/runtest b/bin/runtest
--- a/bin/runtest
+++ b/bin/runtest
@@ -118,6 +118,34 @@ REPORT_ERR()
     PRINT "$ERRMSG" >> $FAILEDLOG
 }
 
+# Report errors
+# $1--an error message to be printed
+REPORT_SYS_ERR()
+{
+    ERRMSG=$1
+    # print it with a banner shifted right a bit
+    PRINT "	*************************************"
+    PRINT "	`date`"
+    PRINT "	$ERRMSG"
+    PRINT "	*************************************"
+    # report it in the SYSERR-LOG file too
+    PRINT "$ERRMSG" >> $SYSERRLOG
+}
+
+# Report errors
+# $1--an error message to be printed
+REPORT_INC_ERR()
+{
+    ERRMSG=$1
+    # print it with a banner shifted right a bit
+    PRINT "	*************************************"
+    PRINT "	`date`"
+    PRINT "	$ERRMSG"
+    PRINT "	*************************************"
+    # report it in the INCOMPLETE-LOG file too
+    PRINT "$ERRMSG" >> $INCOMPLETELOG
+}
+
 #
 # Report results of the last test done
 REPORT_RESULT()
@@ -379,7 +407,8 @@ RUNSNAPTEST()
                 ;;
 	    *) # unknown test
 		PRINT "$0: unknown type of test ($1)"
-		echo "$0: unknown type of test ($1)" >> $FAILEDDETAIL
+		echo "****SYSTEM ERROR $HOST_NAME: unknown type of test ($1)" >> $SYSERRLOG
+                sys_err=1
 		retcode=1
 		;;
 	esac
@@ -406,6 +435,22 @@ RUNSNAPTEST()
     if [ -n "${SRCDIRNAME}" ]; then
         if [ -n "$BATCHMODE" ]; then
             SRCDIRNAME="$SRCDIRNAME-$n_test"
+        else
+            case "$SRCDIRNAME" in
+            "")
+                 SRCDIRNAME=$HOSTNAME
+                 ;;
+            -*)
+                 SRCDIRNAME="$HOSTNAME$SRCDIRNAME"
+                 ;;
+            esac
+        fi
+        TESTDIR=${BASEDIR}/TestDir/${SRCDIRNAME}
+        test -d ${TESTDIR} || mkdir ${TESTDIR}
+        if ! [ -d ${TESTDIR} ]; then
+            REPORT_SYS_ERR "****SYSTEM ERROR ${HOST_NAME}: Could not create ${TESTDIR}"
+            sys_err=1
+            return
         fi
 	SNAPCMD_OPT="$SNAPCMD_OPT srcdirname ${SRCDIRNAME}"
         echo "SRCDIRNAME is $SRCDIRNAME"
@@ -692,6 +737,7 @@ while [ $# -gt 0 ]; do
             ;;
 	-*) # Unknown option
 	    PRINT "Unknown option ($1)"
+            REPORT_SYS_ERR "****SYSTEM ERROR ${HOST_NAME}: Unknown option ($1)"
 	    USAGE
 	    exit 1
 	    ;;
@@ -730,6 +776,7 @@ if test x-$CMD = x-setup; then
     test $errcode -ne 0 && exit 1
 elif [ ! -d ${BASEDIR} ]; then
     echo "BASEDIR ($BASEDIR) does not exist"
+    REPORT_SYS_ERR "****SYSTEM ERROR ${HOST_NAME}: BASEDIR ($BASEDIR) does not exist"
     exit 1
 fi
 # Show the real physical path rather than the symbolic path
@@ -741,9 +788,12 @@ PASSEDLOG=${LOGDIR}/PASSED_LOG_${TODAY}
 FAILEDLOG=${LOGDIR}/FAILED_LOG_${TODAY}
 FAILEDDETAIL=${LOGDIR}/FAILED_DETAIL_${TODAY}
 SKIPPEDLOG=${LOGDIR}/SKIPPED_LOG_${TODAY}
+INCOMPLETELOG=${LOGDIR}/INCOMPLETE_LOG_${TODAY}
+SYSERRLOG=${LOGDIR}/SYSERR_LOG_${TODAY}
+NODIFFLOG=${LOGDIR}/NODIFF_LOG_${TODAY}
 TIMELOG=${LOGDIR}/TIME_LOG_${TODAY}
 TIMEKEEPERLOG=${LOGDIR}/TIMEKEEPER_LOG_${TODAY}
-#REPORTED=${LOGDIR}/REPORTED_${TODAY}
+REPORTED=${LOGDIR}/REPORTED_${TODAY}
 CVSLOG=${LOGDIR}/CVS_LOG_${TODAY}
 CVSLOG_LOCK=${LOGDIR}/CVS_LOG_LOCK_${TODAY}
 DIFFLOG=${LOGDIR}/DIFF_LOG_${TODAY}
@@ -803,7 +853,7 @@ fi
 # Setup to print a trailer summary when exiting not via
 # the normal end of the script.
 #################################
-trap PRINT_TRAILER 0
+#trap PRINT_TRAILER 0 1 2 9 15
 
 #
 TotalStartTime=`SecOfDay`
@@ -814,10 +864,10 @@ PRINT STANDARD_OPT=$STANDARD_OPT
 PRINT TEST_TYPES=$TEST_TYPES
 PRINT_BLANK
 
-echo "FTP flag is $FTP"
+#echo "FTP flag is $FTP"
 if [ -n "$FTP" ]; then
     $SNAPSHOT ftp $FTPURL
-    echo "Ran $SNAPSHOT ftp $FTPURL in line 802"
+    echo "Ran $SNAPSHOT ftp $FTPURL in line 870"
 fi
 # Do a checkout if one has not been done today.
 # Then check MANIFEST file and copyrights noitces.
@@ -833,7 +883,7 @@ if [ -z "$NOCVS" ]; then
     rm -f $CVSLOG_LOCK
     if [ $errcode -ne 0 ]; then
 	# test failed.
-	REPORT_ERR "****FAILED ${HOST_NAME}: CVS checkout****"
+	REPORT_SYS_ERR "****SYSTEM ERROR ${HOST_NAME}: CVS checkout****"
 	exit $errcode
     fi
     # ===================
@@ -911,13 +961,13 @@ else
     WAITFOR $CVSLOG 90
     if [ $WAIT_STATUS -ne 0 ]; then
 	errcode=$WAIT_STATUS
-	REPORT_ERR "****FAILED ${HOST_NAME}: Time expired waiting CVS update to start****"
+	REPORT_SYS_ERR "****SYSTEM ERROR ${HOST_NAME}: Time expired waiting CVS update to start****"
 	exit $errcode
     fi
     WAITTILL $CVSLOG_LOCK 10
     if [ $WAIT_STATUS -ne 0 ]; then
 	errcode=$WAIT_STATUS
-	REPORT_ERR "****FAILED ${HOST_NAME}: Time expired waiting CVS update to finish****"
+	REPORT_SYS_ERR "****SYSTEM ERROR ${HOST_NAME}: Time expired waiting CVS update to finish****"
 	exit $errcode
     fi
 fi
@@ -934,7 +984,7 @@ if [ -z "$NODIFF" ]; then
     if [ -z "$DEBUGMODE" -a $errcode -eq 0 ]; then
 	# no need to run test
 	PRINT "NO TEST: no significant differences between current and previous versions" |
-	    tee -a $PASSEDLOG
+	    tee -a $NODIFFLOG
 	exit 0
     fi
 fi
@@ -978,20 +1028,24 @@ if [ -n "$TESTHOST" -a $HOST_NAME != "$TESTHOST" ]; then
 
 		# launch concurrent tests only if srcdir is used
 		if [ -n "$SRCDIR" ]; then
-		    $CMD || echo "****FAILED ${h}: Abnormal exit from runtest ****" && PRINT_BLANK &
+		    $CMD || echo "****SYSTEM ERROR ${h}: Abnormal exit from runtest ****" && PRINT_BLANK &
 		    echo $! > PID.${h}_${CONFIGNAME}
 		else
-		    $CMD || echo "****FAILED ${h}: Abnormal exit from runtest ****" && PRINT_BLANK
+		    $CMD || echo "****SYSTEM ERROR ${h}: Abnormal exit from runtest ****" && PRINT_BLANK
 		fi
 		;;
 	    NoRemoteCommand)
 		PRINT $h does not accept Remote Command "(`date`)"
+                REPORT_SYS_ERR "****SYSTEM ERROR: ${h} does not accept Remote Command (`date`)" 
 		;;
 	    NotReachable)
 		PRINT $h is not reachable  "(`date`)"
+                REPORT_SYS_ERR "****SYSTEM ERROR: ${h} is not reachable (`date`)"
+
 		;;
 	    *)
 		PRINT "CHECK_RSH for $h returned unknown result ($RSH)"
+                REPORT_SYS_ERR "****SYSTEM ERROR: CHECK_RSH for $h returned unknown result ($RSH)"
 		;;
 	esac >> $TMP_OUTPUT 2>&1
     done
@@ -1007,11 +1061,11 @@ if [ -n "$TESTHOST" -a $HOST_NAME != "$TESTHOST" ]; then
 	# Verify test script did complete by checking the last lines
 	if (tail -3 $TMP_OUTPUT | grep -s 'Abnormal' > /dev/null 2>&1) ; then
             echo "Runtest did not exit normally." >> $FAILEDDETAIL
-           (REPORT_ERR "****FAILED ${h}: runtest command failed ****" &&
+           (REPORT_SYS_ERR "****SYSTEM ERROR ${h}: runtest command failed ****" &&
                 PRINT_BLANK)
         else          
             (tail -3 $TMP_OUTPUT | grep -s 'Grand total' > /dev/null 2>&1) ||
-	    (REPORT_ERR "****FAILED ${h}: snaptest did not complete****" &&
+	    (REPORT_INC_ERR "****INCOMPLETE ${h}: snaptest did not complete****" &&
 		PRINT_BLANK)
         fi
 	rm -f $TMP_OUTPUT PID.${h}_${CONFIGNAME}
@@ -1031,11 +1085,10 @@ fi
 #
 cd $SNAPYARD
 PWD=`pwd` 
-echo "Running $SNAPSHOT checkout from ${PWD}"
-echo "FTP flag is $FTP"
+#echo "FTP flag is $FTP"
 if [ -n "$FTP" ]; then
     $SNAPSHOT ftp $FTPURL
-    echo "Ran $SNAPSHOT ftp $FTPURL in line 979"
+    echo "Ran $SNAPSHOT ftp $FTPURL in line 1087"
 #else
 #    $SNAPSHOT checkout
 #    echo "Ran $SNAPSHOT checkout"
@@ -1053,6 +1106,7 @@ fi
 TEST="`echo $TEST_TYPES | cut -f$n_test -d';'`"
 while [ -n "$TEST" ]; do
     echo "Running $TEST"
+    sys_err=0
     StartTime=`SecOfDay`
     RUNSNAPTEST $TEST 
     if [ -n "$BATCHMODE" ]; then
@@ -1066,7 +1120,9 @@ while [ -n "$TEST" ]; do
         n_test=`expr $n_test + 1`
         TEST="`echo $TEST_TYPES | cut -f$n_test -s -d';'`"
     else
-        REPORT_RESULT
+        if [ $sys_err = 0 ]; then
+            REPORT_RESULT
+        fi
         PRINT_TEST_TRAILER
         EndTime=`SecOfDay`
         duration=`expr $EndTime - $StartTime`
@@ -1107,8 +1163,8 @@ if [ -n "$BATCHMODE" ]; then
       fi
 
       if [ "$retcode" -eq 1 ]; then      
-         # Dump the first 10 lines and the last 30 lines of the LOGFILE.
-         ( ntail=30
+         # Dump the first 10 lines and the last 50 lines of the LOGFILE.
+         ( ntail=50
             echo =========================
             echo "Dumping logfile ${file}: $TEST_TYPE"
             echo "Last $ntail lines of $file"
@@ -1130,5 +1186,5 @@ PRINT_TRAILER
 
 # disable trailer summary printing since all trailers have been
 # printed and we are exiting normally.
-trap 0
+#trap 0
 exit $errcode
diff --git a/bin/snapshot b/bin/snapshot
--- a/bin/snapshot
+++ b/bin/snapshot
@@ -29,7 +29,7 @@ TIMESTAMP()
 
 EXIT_BANNER()
 {
-TIMESTAMP "Exit $PROGNAME with status=$?"
+    TIMESTAMP "Exit $PROGNAME with status=$?"
 }
 
 # Show current total disk usage.
@@ -69,7 +69,7 @@ RUNCONFIGURE()
         cd ${TESTDIR}
         ./${CONFIGURE}
     else 
-        ${CURRENT}/${CONFIGURE}
+        ${CURRENT}/${CONFIGURE} 
     fi
 }
 
@@ -545,23 +545,29 @@ if [ "$cmd" = "all" -o -n "$cmdtest" -o -n "$cmddiff" ]; then
     echo "snapshot is $snapshot"
     # Build, run tests and install procedures
     if [ "$snapshot" = "yes" ] && [ "$NOMAKE" != "yes" ]; then
+        FAIL_SECTION="" 
+        if [ -f ${TESTDIR}/failsection ]; then
+            rm ${TESTDIR}/failsection
+        fi
 	if (cd ${TESTDIR} && \
-	    TIMESTAMP "configure" && \
+	    TIMESTAMP "configure" && echo "configure" > ${TESTDIR}/failsection && \
 	    RUNCONFIGURE && \
             sleep 2 && \
-	    TIMESTAMP "make" && \
+	    TIMESTAMP "make" && echo "make" > ${TESTDIR}/failsection && \
 	    ${MAKE} && DISKUSAGE \
-	    TIMESTAMP ${CHECKVAL} && \
+	    TIMESTAMP ${CHECKVAL} && echo "make check" > ${TESTDIR}/failsection &&  \
 	    ${MAKE} ${CHECKVAL} && DISKUSAGE \
-	    TIMESTAMP "install" && \
+	    TIMESTAMP "install" && echo "make install" > ${TESTDIR}/failsection && \
 	    ${MAKE} install && DISKUSAGE \
-            TIMESTAMP "check-install" && \
+            TIMESTAMP "check-install" && echo "make check-install" > ${TESTDIR}/failsection && \
 	    CHECKINSTALL && DISKUSAGE \
-	    TIMESTAMP "uninstall" && \
+	    TIMESTAMP "uninstall" && echo "make uninstall" > ${TESTDIR}/failsection && \
 	    ${MAKE} uninstall) && DISKUSAGE ; then
 	    :
 	else
 	    errcode=$?
+            FAIL_SECTION=`cat ${TESTDIR}/failsection`
+            echo "Failed running ${FAIL_SECTION}"
 	    snapshot=no
 	    exit $errcode
 	fi
