Correct syntax error in runtest.

diff --git a/bin/runtest b/bin/runtest
--- a/bin/runtest
+++ b/bin/runtest
@@ -422,8 +422,6 @@ RUNSNAPTEST()
     if [ -n "$BATCHMODE" ]; then
         (
         cd $SNAPYARD
-        PWD=`pwd`
-        echo "Submitting $SNAPSHOT $SNAPCMD $SNAPCMD_OPT as batch job from ${PWD}"
         perl bin/batch-$CONFIGNAME-runsnaptest.pl $SNAPSHOTNAME $SRCDIRNAME $LOGFILE $SNAPSHOT $SNAPCMD $SNAPCMD_OPT
         ) >> $LOGFILE 
     else
@@ -1067,9 +1065,19 @@ if [ -n "$BATCHMODE" ]; then
 
    OUTPUTFILES=`ls log/$HOST_NAME-*`
    for file in $OUTPUTFILES; do
-      retcode=0
-      if ! (tail -3 $file | grep -s 'Exit bin/snapshot with status=0' > /dev/null 2>&1) || (grep "FAILED" $file); then
-         retcode=1
+      retcode=1
+      TEST_TYPE=`head $file | grep "bin/snapshot"`
+#      if ! (tail -3 $file | grep -s 'Exit bin/snapshot with status=0' > /dev/null 2>&1) || (grep "FAILED" $file); then
+#         retcode=1
+      if (tail -3 $file | grep -s 'Exit bin/snapshot with status=0' > /dev/null 2>&1); then
+         if (grep "FAILED" $file); then
+            retcode=1
+         else
+            retcode=0
+         fi
+      fi
+
+      if [ "$retcode" -eq 1 ]; then      
          # Dump the first 10 lines and the last 30 lines of the LOGFILE.
          ( ntail=30
             echo =========================
