Changes to make one set of daily test scripts run all daily tests.

diff --git a/bin/snapshot b/bin/snapshot
--- a/bin/snapshot
+++ b/bin/snapshot
@@ -41,7 +41,21 @@ DISKUSAGE()
 
 EXTRACT()
 {
-   echo "Error:  ${sw} is in svn repository - does not need extraction."
+   echo "Error:  ${SWVERSION} is in svn repository - does not need extraction."
+}
+
+SVNCHECKOUT()
+{
+   SVNROOT=https://svn.hdfgroup.uiuc.edu
+   cd $BASEDIR/current; svn info
+   if [ "$?" = "0" ];then
+      echo "Updating $BASEDIR/current from svn."
+      ( svn -q update ) || exit 1
+   else
+      echo "Checking out from $SVNROOT/${SVNVERSION} into $BASEDIR/current"
+      # Check out the current version from source repository.
+      (cd $BASEDIR; svn -q co ${SVNROOT}/${SVNVERSION} current ) || exit 1
+   fi
 }
 
 RUNCONFIGURE()
@@ -66,23 +80,95 @@ CHECKINSTALL()
 #Put this in override file for tests supporting check-install
 #     TIMESTAMP "check-install $1" 
 #     ${MAKE} check-install $1
-    echo "check-install is not supported for ${sw}"
+    echo "check-install is not supported for ${SWVERSION}"
 }
 
-COMMITSNAPSHOT
+COMMITSNAPSHOT()
 {
     echo "original hdf5 script checked code back into svn at this point."
+}
+
+DISPLAYUSAGE()
+{
+    set -
+    cat <<EOF
+Usage: $PROGNAME [all] [checkout] [ftp <URL> [diff] [test] [srcdir] [release] [help]
+	[clean] [distclean] [echo] [deploy <dir>] [deploydir <dir>]
+	[zlib <zlib_path>] [releasedir <dir>] [srcdirname <dir>] [check-vfd]
+	[op-configure <option>] [--<option>]
+    all:      Run all commands (checkout, test & release)
+              [Default is all]
+    checkout: Run source checkout
+    diff:     Run diff on current and previous versions.  Exit 0 if
+              no significant differences are found.  Otherwise, non-zero.
+    deploy:   deploy binary to directory <dir>
+    deploydir: use <dir> as the default directory for deployment
+    test:     Run test
+    release:  Run release
+    clean:    Run make clean
+    distclean:Run make distclean
+    echo:     Turn on echo mode (set -x)
+    setenv <name> <value>:
+              Set environment variable <name> to <value>.
+    setenvN <N> <name> <value> ...:
+	      Set environment variable with <N> values.
+	      E.g., setenvN 3 x a b c is same as setenv x="a b c".
+    srcdir:   Use srcdir option (does not imply other commands)
+              "snapshot srcdir" is equivalent to "snapshot srcdir all"
+              "snapshot srcdir checkout" is equivalent to "snapshot checkout"
+    srcdirname <dir>:
+              Use <dir> as the srcdir testing directory if srcdir is choosen.
+              If <dir> starts with '-', it is append to the default name
+              E.g., "snapshot srcdir srcdirname -xx" uses hostname-xx
+              [Default is hostname]
+    help:     Print this message
+    echo:     Turn on shell echo
+    zlib <zlib_path>:
+              Use <zlib_path> as the ZLIB locations
+              [Default is $ZLIB_default]
+    releasedir <dir>:
+              Use <dir> as the release directory
+              [Default is $ReleaseDir_default]
+    check-vfd:
+	      Run make check-vfd instead of just make check.
+    exttest <testscript>;
+              Run testscript;
+    op-configure <option>:
+              Pass <option> to the configure command
+              E.g., "snapshot op-configure --enable-parallel"
+                  configures for parallel mode
+    --<option>:
+              Pass --<option> to the configure command
+              E.g., "snapshot --enable-parallel"
+                  configures for parallel mode
+EOF
+    exit $errcode
 }
 
 # MAIN
 # SGI /bin/sh replaces $0 as function name if used in a function.
 # Set the name here to avoid that ambiguity and better style too.
 PROGNAME=$0
+SNAPSHOTNAME=
+HDFREPOS=
 
-sw=`pwd | awk -F/ '{print $NF}' | sed -e 's/snapshots-//' -e 's/_[0-9]*//g'`
-if [ -f bin/snapshot-${sw}-overrides ]; then
-    . bin/snapshot-${sw}-overrides
+if [ -f bin/snapshot_params ]; then
+   . bin/snapshot_params
+   echo "Added snapshot_params."
 fi
+if [ -z "$SWVER" -a -f bin/snapshot_version ]
+then
+   . bin/snapshot_version
+   echo "Added snapshot_version."
+fi
+#sw=`pwd | awk -F/ '{print $NF}' | sed -e 's/snapshots-//' -e 's/_[0-9]*//g'`
+#if [ -f bin/snapshot-${sw}-overrides ]; then
+#    . bin/snapshot-${sw}-overrides
+#fi
+if [ -n ${HDFREPOS} -a -f  bin/snapshot-${HDFREPOS}-overrides ]; then
+   . bin/snapshot-${HDFREPOS}-overrides
+   echo "Added snapshot-${HDFREPOS}-overrides."
+fi 
 
 echo "====================================="
 echo "$PROGNAME $*"
@@ -294,59 +380,7 @@ printenv | sort
 echo ===Done Dumping environment variables after option parsing ===
 
 if [ "$cmd" = help ]; then
-    set -
-    cat <<EOF
-Usage: $PROGNAME [all] [checkout] [ftp <URL> [diff] [test] [srcdir] [release] [help]
-	[clean] [distclean] [echo] [deploy <dir>] [deploydir <dir>]
-	[zlib <zlib_path>] [releasedir <dir>] [srcdirname <dir>] [check-vfd]
-	[op-configure <option>] [--<option>]
-    all:      Run all commands (checkout, test & release)
-              [Default is all]
-    checkout: Run source checkout
-    diff:     Run diff on current and previous versions.  Exit 0 if
-              no significant differences are found.  Otherwise, non-zero.
-    deploy:   deploy binary to directory <dir>
-    deploydir: use <dir> as the default directory for deployment
-    test:     Run test
-    release:  Run release
-    clean:    Run make clean
-    distclean:Run make distclean
-    echo:     Turn on echo mode (set -x)
-    setenv <name> <value>:
-              Set environment variable <name> to <value>.
-    setenvN <N> <name> <value> ...:
-	      Set environment variable with <N> values.
-	      E.g., setenvN 3 x a b c is same as setenv x="a b c".
-    srcdir:   Use srcdir option (does not imply other commands)
-              "snapshot srcdir" is equivalent to "snapshot srcdir all"
-              "snapshot srcdir checkout" is equivalent to "snapshot checkout"
-    srcdirname <dir>:
-              Use <dir> as the srcdir testing directory if srcdir is choosen.
-              If <dir> starts with '-', it is append to the default name
-              E.g., "snapshot srcdir srcdirname -xx" uses hostname-xx
-              [Default is hostname]
-    help:     Print this message
-    echo:     Turn on shell echo
-    zlib <zlib_path>:
-              Use <zlib_path> as the ZLIB locations
-              [Default is $ZLIB_default]
-    releasedir <dir>:
-              Use <dir> as the release directory
-              [Default is $ReleaseDir_default]
-    check-vfd:
-	      Run make check-vfd instead of just make check.
-    exttest <testscript>;
-              Run testscript;
-    op-configure <option>:
-              Pass <option> to the configure command
-              E.g., "snapshot op-configure --enable-parallel"
-                  configures for parallel mode
-    --<option>:
-              Pass --<option> to the configure command
-              E.g., "snapshot --enable-parallel"
-                  configures for parallel mode
-EOF
-    exit $errcode
+   DISPLAYUSAGE
 fi
 
 # Setup the proper configure option (--with-zlib) to use zlib library
@@ -359,8 +393,7 @@ echo "Configure command is $CONFIGURE"
 # Execute the requests
 snapshot=yes
 
-
-BASEDIR=${HOME}/snapshots-${SWVERSION}
+BASEDIR=${HOME}/snapshots-${SNAPSHOTNAME}
 if [ ! -d ${BASEDIR} ]; then
     echo "BASEDIR ($BASEDIR) does not exist"
     exit 1
@@ -376,7 +409,6 @@ else
     SVNVERSION="$HDFREPOS/trunk"	# use the default (trunk) version
 fi
 echo "CURRENT is $CURRENT"
-
 
 # Try finding a version of diff that supports the -I option too.
 DIFF=diff
@@ -431,16 +463,7 @@ if [ "$cmd" = "all" -o -n "$cmdcheckout" ]; then
             EXTRACT
         fi
     else
-        SVNROOT=http://svn.hdfgroup.uiuc.edu
-        cd $BASEDIR/current; svn info
-        if [ "$?" = "0" ];then
-            echo "Updating $BASEDIR/current from svn."
-            ( svn -q update ) || exit 1
-        else 
-            echo "Checking out from $SVNROOT/${SVNVERSION} into $BASEDIR/current"
-            # Check out the current version from source repository.
-            (cd $BASEDIR; svn -q co ${SVNROOT}/${SVNVERSION} current ) || exit 1
-        fi
+        SVNCHECKOUT
     fi
 fi # Do source checkout
 
