Update source if previously checked out from svn; update snapshot-<testname>./bin from svn.

diff --git a/bin/snapshot b/bin/snapshot
--- a/bin/snapshot
+++ b/bin/snapshot
@@ -377,6 +377,12 @@ done
 #=============================
 if [ "$cmd" = "all" -o -n "$cmdcheckout" ]; then
     TIMESTAMP "checkout"
+    # Update ${BASEDIR}/bin from svn if it exists.  For now we will continue
+    # whether this update succeeds or fails;  in the future we may want to exit
+    # if it fails.
+    if [ -d ${BASEDIR}/bin ];then 
+        ( cd ${BASEDIR}/bin; svn -q update )
+    fi
     # If there is a Makefile in ${CURRENT}, the last test done in it
     # has not been distclean'ed.  They would interfere with other
     # --srcdir build since make considers the files in ${CURRENT}
@@ -413,9 +419,15 @@ if [ "$cmd" = "all" -o -n "$cmdcheckout" ]; then
         fi
     else
         SVNROOT=http://svn.hdfgroup.uiuc.edu
-        echo "Checking out from $SVNROOT/${SVNVERSION} into $BASEDIR/current"
-        # Check out the current version from source repository.
-        (cd $BASEDIR; svn -q co ${SVNROOT}/${SVNVERSION} current ) || exit 1
+        cd $BASEDIR/current; svn info
+        if [ "$?" = "0" ];then
+            echo "Updating $BASEDIR/current from svn."
+            ( svn -q update ) || exit 1
+        else 
+            echo "Checking out from $SVNROOT/${SVNVERSION} into $BASEDIR/current"
+            # Check out the current version from source repository.
+            (cd $BASEDIR; svn -q co ${SVNROOT}/${SVNVERSION} current ) || exit 1
+        fi
     fi
 fi # Do source checkout
 
